package by.http.news.controller;

public enum CommandName {

	REGISTRATION, AUTHORIZATION, USER_TOOLS, USER_ANSWER, INDEX, USER_AUTHORIZATION, USER_REGISTRATION, MAIN,
	USER_UPDATE, USER_DELETE, USER_FORCE, USER_PASSWORD, LOGGEDOUT, NEWS_TOOLS, NEWS_FORCE, NEWS_ADD, NEWS_UPDATE,
	NEWS_DELETE, NEWS_ANSWER, NEWS_CHOOSE, UNKNOWN_COMMAND

}
